my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path
from p_library import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.books_list),
    path('index/', views.index),
    path('publishers/', views.pub_list),
    path('readers/', views.reader_list),
]

my_site/p_library/models.py
from django.db import models


class Author(models.Model):
    full_name = models.TextField()
    birth_year = models.SmallIntegerField()
    country = models.CharField(max_length=2)

    def __str__(self):
        return self.full_name


class Publisher(models.Model):
    pub_name = models.TextField()

    def __str__(self):
        return self.pub_name


class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.TextField()
    description = models.TextField()
    year_release = models.SmallIntegerField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, null=True, on_delete=models.SET_NULL)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    copy_count = models.PositiveSmallIntegerField(default=1)
    reader = models.ForeignKey(
        'Reader', on_delete=models.SET_NULL,
        null=True, blank=True,
        default='',
        related_name='get_book')
    def __str__(self):
        return self.title


class Reader(models.Model):
    name = models.TextField()
    is_friend = models.BooleanField(default=True)

    def __str__(self):
        return self.name
        # return "-".join((str(self.book),
        #                  str(self.name),))

my_site/p_library/views.py
# from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from p_library.models import Book, Publisher, Reader
#from django.core import serializers

def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)

def index(request):
    template = loader.get_template('index.html')
    books = Book.objects.all()
    books_count = books.count()
    biblio_data = {
        "title": "мою библиотеку",
        "books_count": books_count,
        "books": books,
    }
    return HttpResponse(template.render(biblio_data))

def pub_list(request):
    template = loader.get_template('publishers.html')
    publishers = Publisher.objects.all()
    books = Book.objects.all()
    pub_data = {
        "publishers": publishers,
        "books": books,
    }
    return HttpResponse(template.render(pub_data))

def reader_list(request):
    template = loader.get_template('readers.html')
    readers = Reader.objects.all()
    books = Book.objects.all()
    read_data = {
        "readers": readers,
        "books": books,
    }
    return HttpResponse(template.render(read_data))

my_site/p_library/templates/default.html
hello

my_site/p_library/templates/index.html
Добро пожаловать в {{ title }}  <br>
Тут собрано {{ books_count }} книг из моей личной коллекции.

<table border="1">
    {% for book in books %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ book.title }}</td>
        <td>{{ book.ISBN }}</td>
        <td>{{ book.description }}</td>
        <td>{{ book.year_release }}</td>
        <td>{{ book.author.full_name }}</td>
        <td>{{ book.author.country }}</td>
        <td>{%if book.reader %}
            {{ book.reader }}</td>
            {% endif %}
    </tr>
    {% endfor %}
</table>

my_site/p_library/templates/publishers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
</head>
{% for pub in publishers %}
<ul class="list-group list-group-flush font-weight-bold">
    <li class="list-group-item"> {{ pub.pub_name }}
        <ul class="list-group list-group-flush font-weight-normal">
        {% for book in pub.book_set.all %}
            <li class="list-group-item"> {{ book.title }}</li>
        {% endfor %}
        </ul>
    </li>
</ul>
{% endfor %}

my_site/p_library/templates/readers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
</head>
{% for reader in readers %}
<ul class="list-group list-group-flush font-weight-bold">
    <li class="list-group-item"> {{ reader.name }}
        <ul class="list-group list-group-flush font-weight-normal">
        {% for book in reader.get_book.all %}
            <li class="list-group-item"> {{ book.title }}</li>
        {% endfor %}
        </ul>
    </li>
</ul>
{% endfor %}